questions = [
    'Who seems to be an adaptable person ?',
    'Who seems to be an adventurous person ?',
    'Who seems to be an affable person ?',
    'Who seems to be an affectionate person ?',
    'Who seems to be an agreeable person ?',
    'Who seems to be an ambitious person ?',
    'Who seems to be an amiable person ?',
    'Who seems to be an amicable person ?',
    'Who seems to be an amusing person ?',
    'Who seems to be a brave person ?',
    'Who seems to be a bright person ?',
    'Who seems to be a broad-minded person ?',
    'Who seems to be a calm person ?',
    'Who seems to be a careful person ?',
    'Who seems to be a charming person ?',
    'Who seems to be a communicative person ?',
    'Who seems to be a compassionate person ?',
    'Who seems to be a conscientious person ?',
    'Who seems to be a considerate person ?',
    'Who seems to be a convivial person ?',
    'Who seems to be a courageous person ?',
    'Who seems to be a courteous person ?',
    'Who seems to be a creative person ?',
    'Who seems to be a decisive person ?',
    'Who seems to be a determined person ?',
    'Who seems to be a diligent person ?',
    'Who seems to be a diplomatic person ?',
    'Who seems to be a discreet person ?',
    'Who seems to be a dynamic person ?',
    'Who seems to be an easygoing person ?',
    'Who seems to be an emotional person ?',
    'Who seems to be an energetic person ?',
    'Who seems to be an enthusiastic person ?',
    'Who seems to be an exuberant person ?',
    'Who seems to be a  person ?',
    'Who seems to be a fair-minded person ?',
    'Who seems to be a faithful person ?',
    'Who seems to be a fearless person ?',
    'Who seems to be a forceful person ?',
    'Who seems to be a frank person ?',
    'Who seems to be a friendly person ?',
    'Who seems to be a funny person ?',
    'Who seems to be a generous person ?',
    'Who seems to be a gentle person ?',
    'Who seems to be a good person ?',
    'Who seems to be a gregarious person ?',
    'Who seems to be a hard-working person ?',
    'Who seems to be a helpful person ?',
    'Who seems to be an honest person ?',
    'Who seems to be a humorous person ?',
    'Who seems to be an imaginative person ?',
    'Who seems to be an impartial person ?',
    'Who seems to be an independent person ?',
    'Who seems to be an intellectual person ?',
    'Who seems to be an intelligent person ?',
    'Who seems to be an intuitive person ?',
    'Who seems to be an inventive person ?',
    'Who seems to be a kind person ?',
    'Who seems to be a loving person ?',
    'Who seems to be a loyal person ?',
    'Who seems to be a modest person ?',
    'Who seems to be a neat person ?',
    'Who seems to be a nice person ?',
    'Who seems to be an optimistic person ?',
    'Who seems to be a passionate person ?',
    'Who seems to be a patient person ?',
    'Who seems to be a persistent person ?',
    'Who seems to be a pioneering person ?',
    'Who seems to be a philosophical person ?',
    'Who seems to be a placid person ?',
    'Who seems to be a plucky person ?',
    'Who seems to be a polite person ?',
    'Who seems to be a powerful person ?',
    'Who seems to be a practical person ?',
    'Who seems to be a pro-active person ?',
    'Who seems to be a quick-witted person ?',
    'Who seems to be a quiet person ?',
    'Who seems to be a rational person ?',
    'Who seems to be a reliable person ?',
    'Who seems to be a reserved person ?',
    'Who seems to be a resourceful person ?',
    'Who seems to be a romantic person ?',
    'Who seems to be a self-confident person ?',
    'Who seems to be a self-disciplined person ?',
    'Who seems to be a sensible person ?',
    'Who seems to be a sensitive person ?',
    'Who seems to be a shy person ?',
    'Who seems to be a sincere person ?',
    'Who seems to be a sociable person ?',
    'Who seems to be a straightforward person ?',
    'Who seems to be a sympathetic person ?',
    'Who seems to be a thoughtful person ?',
    'Who seems to be a tidy person ?',
    'Who seems to be a tough person ?',
    'Who seems to be an unassuming person ?',
    'Who seems to be an understanding person ?',
    'Who seems to be a versatile person ?',
    'Who seems to be a warmhearted person ?',
    'Who seems to be a willing person ?',
    'Who seems to be a witty person ?',

    'Who seems to work as a Metallurgical Engineering ?',
    'Who seems to work as a Speech Writer ?',
    'Who seems to work as an Agricultural Scientist ?',
    'Who seems to work as a Statistician ?',
    'Who seems to work as a Network Operator ?',
    'Who seems to work as a Restaurant Manager ?',
    'Who seems to work as a Construction Manager ?',
    'Who seems to work as a Relocation Manager ?',
    'Who seems to work as a Lawyer ?',
    'Who seems to work as a Food & Beverage Director ?',
    'Who seems to work as a Gourmet Chef ?',
    'Who seems to work as a Credit Analyst ?',
    'Who seems to work as an EEO Compliance Manager ?',
    'Who seems to work as an Interior Decorator ?',
    'Who seems to work as an MIS Manager ?',
    'Who seems to work as an Advertising Director ?',
    'Who seems to work as an International Acct. ?',
    'Who seems to work as a Trainer Translator ?',
    'Who seems to work as a Multimedia Director ?',
    'Who seems to work as a Scientific Programmer ?',
    'Who seems to work as a Merchandiser ?',
    'Who seems to work as a Risk Analyst ?',
    'Who seems to work as a Project Manager ?',
    'Who seems to work as a Recruiter ?',
    'Who seems to work as a Mental Health Counselor ?',
    'Who seems to work as a Tour Escort ?',
    'Who seems to work as a Broadcaster ?',
    'Who seems to work as a Seminar Presenter ?',
    'Who seems to work as a Risk Analyst ?',
    'Who seems to work as an Administrator ?',
    'Who seems to work as a Supply Chain Director ?',
    'Who seems to work as a Leasing Manager ?',
    'Who seems to work as a Technical Illustrator ?',
    'Who seems to work as an Administrative Asst. ?',
    'Who seems to work as a Sociologist ?',
    'Who seems to work as a Travel Agent ?',
    'Who seems to work as an Air Traffic Controller ?',
    'Who seems to work as an Investigator ?',
    'Who seems to work as a Seminar Presenter ?',
    'Who seems to work as a Fitness Consultant ?',
    'Who seems to work as a Health Therapist ?',
    'Who seems to work as a Benefits Manager ?',
    'Who seems to work as an EEO Compliance Manager ?',
    'Who seems to work as a Broker ?',
    'Who seems to work as a Nuclear Engineer ?',
    'Who seems to work as a Consultant ?',
    'Who seems to work as an Animal Trainer ?',
    'Who seems to work as an Occupational Therapist ?',
    'Who seems to work as an Operations Research Director ?',
    'Who seems to work as a Political Analyst ?',
    'Who seems to work as an Executive Recruiter ?',
    'Who seems to work as a Production Planner ?',
    'Who seems to work as an Agricultural Scientist ?',
    'Who seems to work as a Producer ?',
    'Who seems to work as an Executive Assistant ?',
    'Who seems to work as a Developer ?',
    'Who seems to work as a Principal ?',
    'Who seems to work as a Hotel Manager ?',
    'Who seems to work as a Flight Attendant ?',
    'Who seems to work as an Account Executive ?',
    'Who seems to work as a Metallurgical Engineering ?',
    'Who seems to work as an Industrial Designer ?',
    'Who seems to work as a Radiology Manager ?',
    'Who seems to work as an Electro Optical Engineer ?',
    'Who seems to work as a Motion Picture Director ?',
    'Who seems to work as a Political Analyst ?',
    'Who seems to work as a Broadcaster ?',
    'Who seems to work as a City Housing Manager ?',
    'Who seems to work as a Corporate Planner ?',
    'Who seems to work as a Franchise Sales ?',
    'Who seems to work as a PR Specialist ?',
    'Who seems to work as a Production Engineer ?',
    'Who seems to work as a Computer Programmer ?',
    'Who seems to work as a Radiology Manager ?',
    'Who seems to work as a Restaurant Manager ?',
    'Who seems to work as a Seminar Presenter ?',
    'Who seems to work as a City Manager ?',
    'Who seems to work as a Mechanical Engineer ?',
    'Who seems to work as a Regulatory Affairs Manager ?',
    'Who seems to work as a Quality Control Engineer ?',
    'Who seems to work as a Probation Officer ?',
    'Who seems to work as an Organizational Development Manager ?',
    'Who seems to work as an Escrow Officer ?',
    'Who seems to work as an Executive Assistant ?',
    'Who seems to work as a Producer ?',
    'Who seems to work as a Stockbroker ?',
    'Who seems to work as a Nursing Administrator ?',
    'Who seems to work as an Outplacement Specialist ?',
    'Who seems to work as an Operations Manager ?',
    'Who seems to work as a Chief Information Officer ?',
    'Who seems to work as a Glamour Photographer ?',
    'Who seems to work as a City Housing Manager ?',
    'Who seems to work as a Computer Operator ?',
    'Who seems to work as a Cryptologist ?',
    'Who seems to work as an IT Architect ?',
    'Who seems to work as an Executive Director ?',
    'Who seems to work as a Comptroller ?',
    'Who seems to work as a Professor ?',
    'Who seems to work as an Artist ?',
    'Who seems to work as a Film Production Assistant ?'
]

export default questions;